import type { Metadata } from "next";
import './globals.css';
import ServerWrapper from '@/app/ServerWrapper';

export const metadata: Metadata = {
  title: "Learn English with doubleK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ServerWrapper>{children}</ServerWrapper>
      </body>
    </html>
  );
}
